name: main

on:
  pull_request:
  push:
    branches:
    - main
 

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          opam-pin: false
          opam-depext: false
          ocaml-compiler: ocaml.5.1.0
          opam-repositories: |
            upstream: https://github.com/ocaml/opam-repository.git
          
      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest